version: "2"
prepare:
  # rules from https://github.com/visenze/codestyle
  fetch:
  - "https://raw.githubusercontent.com/visenze/codestyle/master/typescript/tslint.json"
  - "https://raw.githubusercontent.com/visenze/codestyle/master/javascript/.eslintrc.json"
  - "https://raw.githubusercontent.com/visenze/codestyle/master/scss/.scss-lint.yml"
plugins:
  # https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)
  duplication:
    enabled: true
    config:
      count_threshold: 3
  # java
  sonar-java:
    enabled: true
    checks:
      squid:S3776:
        enabled: false
    config:
      minimum_severity: critical
      tests_patterns:
      - "**/src/test/**"
  # python
  sonar-python:
    enabled: true
    checks:
      python:S3776:
        enabled: false
  # c++
  cppcheck:
    enabled: true
  # golang
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  # typescript
  tslint:
    enabled: true
    config: tslint.json
  # scss
  scss-lint:
    enabled: true
  # javascript
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
  # swift
  tailor:
    enabled: false
# https://docs.codeclimate.com/docs/excluding-files-and-folders
exclude_patterns:
- "**/vendor/"
- "**/3rdparty/"
- "**/*.conf.js"
- "**/*.config.js"
# https://docs.codeclimate.com/docs/maintainability
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
    config:
      # 3x relaxed from the default threshold
      # So it is 60 for golang and 15 for all the other languages
      threshold: 15
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: true
