version: "2"
prepare:
  fetch:
  - "https://raw.githubusercontent.com/visenze/codestyle/master/typescript/tslint.json"
  - "https://raw.githubusercontent.com/visenze/codestyle/master/javascript/.eslintrc.json"
  - "https://raw.githubusercontent.com/visenze/codestyle/master/scss/.scss-lint.yml"
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
  sonar-java:
    config:
      minimum_severity: critical
    tests_patterns:
    - "**/src/test/**"
  sonar-python:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
  scss-lint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
exclude_patterns:
- "**/vendor/"
- "**/3rdparty/"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: true
